"""PC tools for the Mars Scout Rover RPLIDAR C1 subsystem."""

from .c1_pc_direct import (
    BytesBufferTransport,
    C1CaptureConfig,
    C1DecodedSample,
    C1DriverError,
    C1HardwareAccessError,
    C1PcDirectDriver,
    C1ProtocolError,
    C1StandardScanParser,
    C1TimeoutError,
    PySerialByteTransport,
    capture_c1_session,
    decoded_sample_to_scan_point,
    parse_sample_hex,
)
from .coordinate_transform import (
    native_c1_angle_to_rover_deg,
    native_clockwise_to_robot_angle_deg,
    normalize_angle_deg,
    normalize_angle_rad,
    polar_to_cartesian,
    polar_to_cartesian_m,
    scan_frame_to_cartesian,
    scan_point_to_cartesian,
    transform_point_2d,
)
from .data_models import CartesianPoint, LidarSample, LidarScan, RawLidarSample
from .data_models import ScanFrame, ScanPoint, Transform2D
from .data_models import ScanSource
from .point_cloud_view import create_point_cloud_figure, save_point_cloud_view
from .polar_view import create_polar_figure, save_polar_view
from .recorder import MultiSensorRecorder, RecordingError
from .recording_models import (
    BarometerSample,
    GroundEdgeSample,
    HallLandmarkSample,
    IlluminanceSample,
    ImuSample,
    RoverPose,
    SCHEMA_NAME,
    SCHEMA_VERSION,
    SensorDefinition,
    UltrasonicSample,
    default_sensor_inventory,
)
from .replay import (
    LidarScanRecord,
    RecordingEntry,
    RecordingFormatError,
    RecordingSummary,
    inspect_recording,
    iter_lidar_scans,
    iter_recording_entries,
    last_lidar_scan_by_sensor,
    read_recording_header,
    replay_lidar_scans,
)
from .scan_builder import ScanValidationError, build_scan_frame, create_scan_point
from .stm32_recording_bridge import (
    bridge_stm32_message_to_recording,
    record_stm32_telemetry_stream,
    stm32_message_to_recording_sample,
)
from .stm32_sensor_models import (
    STM32_TELEMETRY_PROTOCOL,
    STM32_TELEMETRY_VERSION,
    Stm32TelemetryMessage,
)
from .stm32_sensor_protocol import (
    Stm32TelemetryError,
    Stm32TelemetryFormatError,
    encode_stm32_telemetry_message,
    iter_stm32_telemetry,
    parse_stm32_telemetry_line,
    validate_stm32_telemetry_message,
)
from .stm32_sensor_simulator import (
    STM32_SIMULATOR_SCENARIOS,
    generate_synthetic_stm32_lines,
    generate_synthetic_stm32_session,
)
from .synthetic_scan import (
    SyntheticRoomConfig,
    SyntheticScanSource,
    generate_circle_scan,
    generate_room_scan,
)

__all__ = [
    "CartesianPoint",
    "LidarSample",
    "LidarScan",
    "LidarScanRecord",
    "MultiSensorRecorder",
    "RawLidarSample",
    "RecordingEntry",
    "RecordingError",
    "RecordingFormatError",
    "RecordingSummary",
    "RoverPose",
    "SCHEMA_NAME",
    "SCHEMA_VERSION",
    "ScanFrame",
    "ScanPoint",
    "ScanSource",
    "ScanValidationError",
    "SensorDefinition",
    "SyntheticRoomConfig",
    "SyntheticScanSource",
    "UltrasonicSample",
    "BarometerSample",
    "BytesBufferTransport",
    "C1CaptureConfig",
    "C1DecodedSample",
    "C1DriverError",
    "C1HardwareAccessError",
    "C1PcDirectDriver",
    "C1ProtocolError",
    "C1StandardScanParser",
    "C1TimeoutError",
    "build_scan_frame",
    "bridge_stm32_message_to_recording",
    "capture_c1_session",
    "create_point_cloud_figure",
    "create_polar_figure",
    "create_scan_point",
    "default_sensor_inventory",
    "decoded_sample_to_scan_point",
    "generate_circle_scan",
    "generate_synthetic_stm32_lines",
    "generate_synthetic_stm32_session",
    "generate_room_scan",
    "GroundEdgeSample",
    "HallLandmarkSample",
    "IlluminanceSample",
    "ImuSample",
    "inspect_recording",
    "iter_lidar_scans",
    "iter_recording_entries",
    "last_lidar_scan_by_sensor",
    "native_c1_angle_to_rover_deg",
    "native_clockwise_to_robot_angle_deg",
    "normalize_angle_deg",
    "normalize_angle_rad",
    "polar_to_cartesian",
    "polar_to_cartesian_m",
    "PySerialByteTransport",
    "parse_sample_hex",
    "parse_stm32_telemetry_line",
    "record_stm32_telemetry_stream",
    "scan_frame_to_cartesian",
    "scan_point_to_cartesian",
    "read_recording_header",
    "replay_lidar_scans",
    "save_point_cloud_view",
    "save_polar_view",
    "STM32_SIMULATOR_SCENARIOS",
    "STM32_TELEMETRY_PROTOCOL",
    "STM32_TELEMETRY_VERSION",
    "Stm32TelemetryError",
    "Stm32TelemetryFormatError",
    "Stm32TelemetryMessage",
    "stm32_message_to_recording_sample",
    "transform_point_2d",
    "Transform2D",
    "validate_stm32_telemetry_message",
]
