"""PC tools for the Mars Scout Rover RPLIDAR C1 subsystem."""

from .c1_pc_direct import (
    BytesBufferTransport,
    C1CaptureConfig,
    C1DecodedSample,
    C1DriverError,
    C1HardwareAccessError,
    C1PcDirectDriver,
    C1ProtocolError,
    C1StandardScanParser,
    C1TimeoutError,
    PySerialByteTransport,
    capture_c1_session,
    decoded_sample_to_scan_point,
    parse_sample_hex,
)
from .coordinate_transform import (
    native_c1_angle_to_rover_deg,
    native_clockwise_to_robot_angle_deg,
    normalize_angle_deg,
    normalize_angle_rad,
    polar_to_cartesian,
    polar_to_cartesian_m,
    scan_frame_to_cartesian,
    scan_point_to_cartesian,
    transform_point_2d,
)
from .data_models import CartesianPoint, LidarSample, LidarScan, RawLidarSample
from .data_models import ScanFrame, ScanPoint, Transform2D
from .data_models import ScanSource
from .openrf1_bh1750 import (
    BH1750_ONE_TIME_HIGH_RESOLUTION_MODE,
    OPENRF1_BH1750_ADDRESS_7BIT,
    OPENRF1_BH1750_SENSOR_ID,
    OPENRF1_BOARD_NAME,
    OPENRF1_MCU,
    Bh1750Controller,
    Bh1750Sample,
    OpenRf1Bh1750Error,
    OpenRf1BoardConfig,
    bh1750_raw_count_from_bytes,
    bh1750_raw_count_to_centilux,
    bh1750_raw_count_to_lux,
    bh1750_read_address_byte,
    bh1750_write_address_byte,
    format_bh1750_telemetry_line,
    generate_bh1750_telemetry_lines,
)
from .point_cloud_view import create_point_cloud_figure, save_point_cloud_view
from .polar_view import create_polar_figure, save_polar_view
from .recorder import MultiSensorRecorder, RecordingError
from .recording_models import (
    BarometerSample,
    GroundEdgeSample,
    HallLandmarkSample,
    IlluminanceSample,
    ImuSample,
    RoverPose,
    SCHEMA_NAME,
    SCHEMA_VERSION,
    SensorDefinition,
    UltrasonicSample,
    default_sensor_inventory,
)
from .replay import (
    LidarScanRecord,
    RecordingEntry,
    RecordingFormatError,
    RecordingSummary,
    inspect_recording,
    iter_lidar_scans,
    iter_recording_entries,
    last_lidar_scan_by_sensor,
    read_recording_header,
    replay_lidar_scans,
)
from .scan_builder import ScanValidationError, build_scan_frame, create_scan_point
from .stm32_recording_bridge import (
    bridge_stm32_message_to_recording,
    record_stm32_telemetry_stream,
    stm32_message_to_recording_sample,
)
from .stm32_sensor_models import (
    STM32_TELEMETRY_PROTOCOL,
    STM32_TELEMETRY_VERSION,
    Stm32TelemetryMessage,
)
from .stm32_sensor_protocol import (
    Stm32TelemetryError,
    Stm32TelemetryFormatError,
    encode_stm32_telemetry_message,
    iter_stm32_telemetry,
    parse_stm32_telemetry_line,
    validate_stm32_telemetry_message,
)
from .stm32_serial_capture import (
    DEFAULT_STM32_SERIAL_BAUD,
    FileChunkSerialReader,
    PySerialLineReader,
    Stm32SerialCaptureError,
    Stm32SerialCaptureInterrupted,
    Stm32SerialCaptureSummary,
    capture_stm32_serial_telemetry,
)
from .stm32_sensor_simulator import (
    STM32_SIMULATOR_SCENARIOS,
    generate_synthetic_stm32_lines,
    generate_synthetic_stm32_session,
)
from .synthetic_scan import (
    SyntheticRoomConfig,
    SyntheticScanSource,
    generate_circle_scan,
    generate_room_scan,
)

__all__ = [
    "CartesianPoint",
    "LidarSample",
    "LidarScan",
    "LidarScanRecord",
    "MultiSensorRecorder",
    "RawLidarSample",
    "RecordingEntry",
    "RecordingError",
    "RecordingFormatError",
    "RecordingSummary",
    "RoverPose",
    "SCHEMA_NAME",
    "SCHEMA_VERSION",
    "ScanFrame",
    "ScanPoint",
    "ScanSource",
    "ScanValidationError",
    "SensorDefinition",
    "SyntheticRoomConfig",
    "SyntheticScanSource",
    "UltrasonicSample",
    "BarometerSample",
    "BH1750_ONE_TIME_HIGH_RESOLUTION_MODE",
    "Bh1750Controller",
    "Bh1750Sample",
    "BytesBufferTransport",
    "C1CaptureConfig",
    "C1DecodedSample",
    "C1DriverError",
    "C1HardwareAccessError",
    "C1PcDirectDriver",
    "C1ProtocolError",
    "C1StandardScanParser",
    "C1TimeoutError",
    "build_scan_frame",
    "bridge_stm32_message_to_recording",
    "capture_c1_session",
    "capture_stm32_serial_telemetry",
    "create_point_cloud_figure",
    "create_polar_figure",
    "create_scan_point",
    "default_sensor_inventory",
    "decoded_sample_to_scan_point",
    "generate_circle_scan",
    "generate_bh1750_telemetry_lines",
    "generate_synthetic_stm32_lines",
    "generate_synthetic_stm32_session",
    "generate_room_scan",
    "GroundEdgeSample",
    "HallLandmarkSample",
    "IlluminanceSample",
    "ImuSample",
    "inspect_recording",
    "iter_lidar_scans",
    "iter_recording_entries",
    "last_lidar_scan_by_sensor",
    "native_c1_angle_to_rover_deg",
    "native_clockwise_to_robot_angle_deg",
    "normalize_angle_deg",
    "normalize_angle_rad",
    "OpenRf1Bh1750Error",
    "OpenRf1BoardConfig",
    "OPENRF1_BH1750_ADDRESS_7BIT",
    "OPENRF1_BH1750_SENSOR_ID",
    "OPENRF1_BOARD_NAME",
    "OPENRF1_MCU",
    "polar_to_cartesian",
    "polar_to_cartesian_m",
    "PySerialByteTransport",
    "PySerialLineReader",
    "parse_sample_hex",
    "parse_stm32_telemetry_line",
    "record_stm32_telemetry_stream",
    "scan_frame_to_cartesian",
    "scan_point_to_cartesian",
    "read_recording_header",
    "replay_lidar_scans",
    "save_point_cloud_view",
    "save_polar_view",
    "FileChunkSerialReader",
    "DEFAULT_STM32_SERIAL_BAUD",
    "STM32_SIMULATOR_SCENARIOS",
    "STM32_TELEMETRY_PROTOCOL",
    "STM32_TELEMETRY_VERSION",
    "Stm32TelemetryError",
    "Stm32TelemetryFormatError",
    "Stm32TelemetryMessage",
    "Stm32SerialCaptureError",
    "Stm32SerialCaptureInterrupted",
    "Stm32SerialCaptureSummary",
    "stm32_message_to_recording_sample",
    "transform_point_2d",
    "Transform2D",
    "validate_stm32_telemetry_message",
    "bh1750_raw_count_from_bytes",
    "bh1750_raw_count_to_centilux",
    "bh1750_raw_count_to_lux",
    "bh1750_read_address_byte",
    "bh1750_write_address_byte",
    "format_bh1750_telemetry_line",
]
