"""PC tools for the Mars Scout Rover RPLIDAR C1 subsystem."""

from .coordinate_transform import (
    native_c1_angle_to_rover_deg,
    native_clockwise_to_robot_angle_deg,
    normalize_angle_deg,
    normalize_angle_rad,
    polar_to_cartesian,
    polar_to_cartesian_m,
    scan_frame_to_cartesian,
    scan_point_to_cartesian,
    transform_point_2d,
)
from .data_models import CartesianPoint, LidarSample, LidarScan, RawLidarSample
from .data_models import ScanFrame, ScanPoint, Transform2D
from .data_models import ScanSource
from .point_cloud_view import create_point_cloud_figure, save_point_cloud_view
from .polar_view import create_polar_figure, save_polar_view
from .recorder import MultiSensorRecorder, RecordingError
from .recording_models import (
    BarometerSample,
    GroundEdgeSample,
    HallLandmarkSample,
    IlluminanceSample,
    ImuSample,
    RoverPose,
    SCHEMA_NAME,
    SCHEMA_VERSION,
    SensorDefinition,
    UltrasonicSample,
    default_sensor_inventory,
)
from .replay import (
    LidarScanRecord,
    RecordingEntry,
    RecordingFormatError,
    RecordingSummary,
    inspect_recording,
    iter_lidar_scans,
    iter_recording_entries,
    last_lidar_scan_by_sensor,
    read_recording_header,
    replay_lidar_scans,
)
from .scan_builder import ScanValidationError, build_scan_frame, create_scan_point
from .synthetic_scan import (
    SyntheticRoomConfig,
    SyntheticScanSource,
    generate_circle_scan,
    generate_room_scan,
)

__all__ = [
    "CartesianPoint",
    "LidarSample",
    "LidarScan",
    "LidarScanRecord",
    "MultiSensorRecorder",
    "RawLidarSample",
    "RecordingEntry",
    "RecordingError",
    "RecordingFormatError",
    "RecordingSummary",
    "RoverPose",
    "SCHEMA_NAME",
    "SCHEMA_VERSION",
    "ScanFrame",
    "ScanPoint",
    "ScanSource",
    "ScanValidationError",
    "SensorDefinition",
    "SyntheticRoomConfig",
    "SyntheticScanSource",
    "UltrasonicSample",
    "BarometerSample",
    "build_scan_frame",
    "create_point_cloud_figure",
    "create_polar_figure",
    "create_scan_point",
    "default_sensor_inventory",
    "generate_circle_scan",
    "generate_room_scan",
    "GroundEdgeSample",
    "HallLandmarkSample",
    "IlluminanceSample",
    "ImuSample",
    "inspect_recording",
    "iter_lidar_scans",
    "iter_recording_entries",
    "last_lidar_scan_by_sensor",
    "native_c1_angle_to_rover_deg",
    "native_clockwise_to_robot_angle_deg",
    "normalize_angle_deg",
    "normalize_angle_rad",
    "polar_to_cartesian",
    "polar_to_cartesian_m",
    "scan_frame_to_cartesian",
    "scan_point_to_cartesian",
    "read_recording_header",
    "replay_lidar_scans",
    "save_point_cloud_view",
    "save_polar_view",
    "transform_point_2d",
    "Transform2D",
]
