#pragma once

#include <stdint.h>
#include "stm32f10x.h"

#define OPENRF1_GROUND_BRINGUP_PHASE "phase3.2f"
#define OPENRF1_GROUND_BOARD_NAME "OpenRF1"
#define OPENRF1_GROUND_MCU_PART "STM32F103RCT6"

#define OPENRF1_GROUND_SENSOR_GROUP_ID "ground_sensors"
#define OPENRF1_GROUND_CONNECTOR "OpenRF1_four_channel_tracking"
#define OPENRF1_GROUND_CONNECTOR_PART "HDGC2001WV-6P"
#define OPENRF1_GROUND_CONNECTOR_PIN1 "GND"
#define OPENRF1_GROUND_CONNECTOR_PIN2 "X4_schematic_PC14_unused"
#define OPENRF1_GROUND_CONNECTOR_PIN3 "X3_PB0"
#define OPENRF1_GROUND_CONNECTOR_PIN4 "X2_PC5"
#define OPENRF1_GROUND_CONNECTOR_PIN5 "X1_PC4"
#define OPENRF1_GROUND_CONNECTOR_PIN6 "VCC_5V"

#define OPENRF1_GROUND_LEFT_CHANNEL_NAME "left_tcrt5000"
#define OPENRF1_GROUND_LEFT_SENSOR_ID "tcrt5000_1"
#define OPENRF1_GROUND_LEFT_CONNECTOR_SIGNAL ((uint8_t)1u)
#define OPENRF1_GROUND_LEFT_CONNECTOR_LABEL "X1"
#define OPENRF1_GROUND_LEFT_PORT GPIOC
#define OPENRF1_GROUND_LEFT_PIN GPIO_Pin_4
#define OPENRF1_GROUND_LEFT_RCC RCC_APB2Periph_GPIOC
#define OPENRF1_GROUND_LEFT_PIN_TEXT "PC4"
#define OPENRF1_GROUND_LEFT_SUPPLY_TEXT "3.3V"

#define OPENRF1_GROUND_RIGHT_CHANNEL_NAME "right_tcrt5000"
#define OPENRF1_GROUND_RIGHT_SENSOR_ID "tcrt5000_2"
#define OPENRF1_GROUND_RIGHT_CONNECTOR_SIGNAL ((uint8_t)2u)
#define OPENRF1_GROUND_RIGHT_CONNECTOR_LABEL "X2"
#define OPENRF1_GROUND_RIGHT_PORT GPIOC
#define OPENRF1_GROUND_RIGHT_PIN GPIO_Pin_5
#define OPENRF1_GROUND_RIGHT_RCC RCC_APB2Periph_GPIOC
#define OPENRF1_GROUND_RIGHT_PIN_TEXT "PC5"
#define OPENRF1_GROUND_RIGHT_SUPPLY_TEXT "3.3V"

#define OPENRF1_GROUND_HALL_CHANNEL_NAME "hall_sensor"
#define OPENRF1_GROUND_HALL_SENSOR_ID "hall_1"
#define OPENRF1_GROUND_HALL_CONNECTOR_SIGNAL ((uint8_t)3u)
#define OPENRF1_GROUND_HALL_CONNECTOR_LABEL "X3"
#define OPENRF1_GROUND_HALL_PORT GPIOB
#define OPENRF1_GROUND_HALL_PIN GPIO_Pin_0
#define OPENRF1_GROUND_HALL_RCC RCC_APB2Periph_GPIOB
#define OPENRF1_GROUND_HALL_PIN_TEXT "PB0"
#define OPENRF1_GROUND_HALL_MODULE_SUPPLY_TEXT "5V"
#define OPENRF1_GROUND_HALL_INPUT_PROTECTION_TEXT "external_10k_15k_divider_required"

#define OPENRF1_GROUND_SIGNAL4_USED ((uint8_t)0u)
#define OPENRF1_GROUND_SIGNAL4_CONNECTOR_SIGNAL ((uint8_t)4u)
#define OPENRF1_GROUND_SIGNAL4_CONNECTOR_LABEL "X4"
#define OPENRF1_GROUND_SIGNAL4_SCHEMATIC_PIN_TEXT "PC14"
#define OPENRF1_GROUND_SIGNAL4_VENDOR_EXAMPLE_PIN_TEXT "PB1"
#define OPENRF1_GROUND_SIGNAL4_MAPPING_CONFLICT "schematic_PC14_vendor_example_PB1"

#define OPENRF1_GROUND_GPIO_MODE_TEXT "floating_input"
#define OPENRF1_GROUND_SAMPLE_PERIOD_MS ((uint32_t)5u)
#define OPENRF1_GROUND_TELEMETRY_PERIOD_MS ((uint32_t)50u)
#define OPENRF1_GROUND_DEBOUNCE_SAMPLES ((uint8_t)4u)
#define OPENRF1_GROUND_EFFECTIVE_DEBOUNCE_MS ((uint32_t)20u)
#define OPENRF1_GROUND_TELEMETRY_BUFFER_BYTES ((uint16_t)1536u)

#define OPENRF1_GROUND_TCRT_SUPPLY_MV ((uint16_t)3300u)
#define OPENRF1_GROUND_HALL_MODULE_SUPPLY_MV ((uint16_t)5000u)
#define OPENRF1_GROUND_HALL_DIVIDER_SERIES_RESISTOR_OHM ((uint16_t)10000u)
#define OPENRF1_GROUND_HALL_DIVIDER_PULLDOWN_RESISTOR_OHM ((uint16_t)15000u)
#define OPENRF1_GROUND_HALL_DIVIDER_TOLERANCE_PERCENT ((uint8_t)5u)

#define OPENRF1_GROUND_DEBUG_USART USART1
#define OPENRF1_GROUND_DEBUG_USART_RCC RCC_APB2Periph_USART1
#define OPENRF1_GROUND_DEBUG_TX_PORT GPIOA
#define OPENRF1_GROUND_DEBUG_TX_PIN GPIO_Pin_9
#define OPENRF1_GROUND_DEBUG_GPIO_RCC RCC_APB2Periph_GPIOA
#define OPENRF1_GROUND_DEBUG_BAUD ((uint32_t)115200u)
#define OPENRF1_GROUND_DEBUG_TX_SPIN_LIMIT ((uint16_t)2000u)
