#pragma once

#include <stdint.h>

#define OPENRF1_ENCODER_BRINGUP_BOARD "OpenRF1_STM32F103RCT6"
#define OPENRF1_ENCODER_BRINGUP_MAPPING_STATUS \
    "vendor_connector_mapping_physical_wheels_unverified"
#define OPENRF1_ENCODER_BRINGUP_COUNTER_BITS ((uint8_t)16u)
#define OPENRF1_ENCODER_BRINGUP_SAMPLE_PERIOD_MS ((uint32_t)100u)
#define OPENRF1_ENCODER_BRINGUP_USART_BAUD ((uint32_t)115200u)
#define OPENRF1_ENCODER_BRINGUP_TX_BUFFER_BYTES ((uint16_t)1024u)
#define OPENRF1_ENCODER_BRINGUP_TELEMETRY_BUFFER_BYTES ((uint16_t)640u)
#define OPENRF1_ENCODER_BRINGUP_TELEMETRY_MAX_BYTES ((uint16_t)599u)

#define OPENRF1_ENCODER_BRINGUP_STATIC_ASSERT(name, expression) \
    typedef char name[(expression) ? 1 : -1]

OPENRF1_ENCODER_BRINGUP_STATIC_ASSERT(
    encoder_bringup_telemetry_fits_buffer,
    OPENRF1_ENCODER_BRINGUP_TELEMETRY_BUFFER_BYTES >=
        OPENRF1_ENCODER_BRINGUP_TELEMETRY_MAX_BYTES
);
OPENRF1_ENCODER_BRINGUP_STATIC_ASSERT(
    encoder_bringup_tx_holds_one_record,
    OPENRF1_ENCODER_BRINGUP_TX_BUFFER_BYTES >
        OPENRF1_ENCODER_BRINGUP_TELEMETRY_BUFFER_BYTES
);
