#pragma once

#include <stdint.h>
#include "stm32f10x.h"

#define OPENRF1_BOARD_NAME "OpenRF1"
#define OPENRF1_BOARD_MANUFACTURER "Yeahbot / Hangzhou Songjia Technology"
#define OPENRF1_MCU_PART "STM32F103RCT6"
#define OPENRF1_VENDOR_TARGET "STM32F103RC"

#define OPENRF1_BH1750_SENSOR_ID "bh1750_1"
#define OPENRF1_BH1750_ADDRESS_7BIT ((uint8_t)0x23u)

#define OPENRF1_SOFT_I2C_SCL_PORT GPIOB
#define OPENRF1_SOFT_I2C_SCL_PIN GPIO_Pin_1
#define OPENRF1_SOFT_I2C_SCL_RCC RCC_APB2Periph_GPIOB

#define OPENRF1_SOFT_I2C_SDA_PORT GPIOC
#define OPENRF1_SOFT_I2C_SDA_PIN GPIO_Pin_3
#define OPENRF1_SOFT_I2C_SDA_RCC RCC_APB2Periph_GPIOC

#define OPENRF1_TELEMETRY_USART USART1
#define OPENRF1_TELEMETRY_USART_RCC RCC_APB2Periph_USART1
#define OPENRF1_TELEMETRY_USART_TX_PORT GPIOA
#define OPENRF1_TELEMETRY_USART_TX_PIN GPIO_Pin_9
#define OPENRF1_TELEMETRY_USART_TX_RCC RCC_APB2Periph_GPIOA
#define OPENRF1_TELEMETRY_USART_RX_PORT GPIOA
#define OPENRF1_TELEMETRY_USART_RX_PIN GPIO_Pin_10
#define OPENRF1_TELEMETRY_USART_RX_RCC RCC_APB2Periph_GPIOA
#define OPENRF1_TELEMETRY_BAUD ((uint32_t)115200u)
#define OPENRF1_TELEMETRY_DATA_BITS 8
#define OPENRF1_TELEMETRY_PARITY_NONE 1
#define OPENRF1_TELEMETRY_STOP_BITS 1

#define OPENRF1_BH1750_MEASUREMENT_TIME_MS ((uint32_t)180u)
#define OPENRF1_BH1750_PERIOD_MS ((uint32_t)500u)
#define OPENRF1_BH1750_RETRY_BACKOFF_MS ((uint32_t)1000u)
#define OPENRF1_SOFT_I2C_ACK_TIMEOUT_TICKS ((uint16_t)200u)
#define OPENRF1_SOFT_I2C_RECOVERY_PULSES ((uint8_t)9u)
#define OPENRF1_TELEMETRY_BUFFER_BYTES ((uint16_t)256u)
