from __future__ import annotations

from pathlib import Path

import pytest

from rplidar_c1_tools.phase25_evidence import (
    CAPTURE_SPECS,
    RVIZ_HEIGHT_PX,
    RVIZ_SHA256,
    RVIZ_WIDTH_PX,
    SOURCE_ARCHIVE_SHA256,
    Phase25EvidenceError,
    validate_all_phase25_captures,
    validate_phase25_capture,
    validate_phase25_rviz_evidence,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
REPORT_PATH = REPO_ROOT / "evidence/phase2.5/c1_1_physical_evidence.md"


def test_phase25_capture_bundle_is_hash_locked_and_structurally_valid() -> None:
    summaries = validate_all_phase25_captures(REPO_ROOT)

    assert len(summaries) == 8
    assert sum(summary.scan_count for summary in summaries) == 102
    assert sum(summary.point_count for summary in summaries) == 36_720
    assert all(summary.point_count == summary.scan_count * 360 for summary in summaries)
    assert all(summary.sequence_start == 1 for summary in summaries)
    assert all(summary.sequence_end == summary.scan_count for summary in summaries)
    assert sum(summary.zero_quality_count for summary in summaries) == 41
    assert sum(summary.over_profile_range_count for summary in summaries) == 132


def test_phase25_rviz_screenshot_is_hash_locked_png() -> None:
    summary = validate_phase25_rviz_evidence(REPO_ROOT)

    assert summary.sha256 == RVIZ_SHA256
    assert (summary.width_px, summary.height_px) == (RVIZ_WIDTH_PX, RVIZ_HEIGHT_PX)
    assert (summary.bit_depth, summary.color_type) == (8, 2)


def test_phase25_validator_rejects_changed_capture(tmp_path: Path) -> None:
    name = "c1_1_live_1x360"
    source = REPO_ROOT / CAPTURE_SPECS[name]["path"]
    changed = tmp_path / "changed.jsonl"
    changed.write_bytes(source.read_bytes().replace(b'"sequence":1', b'"sequence":2', 1))

    with pytest.raises(Phase25EvidenceError, match="sha256"):
        validate_phase25_capture(tmp_path, name, evidence_path=changed)


def test_phase25_report_is_sanitized_and_scope_limited() -> None:
    report = REPORT_PATH.read_text(encoding="utf-8")
    required = [
        SOURCE_ARCHIVE_SHA256,
        RVIZ_SHA256,
        "MANUAL_EVIDENCE_VERIFIED",
        "36,720",
        "132",
        "generated by the capture tool",
        "ROS2/RViz is external diagnostic evidence",
        "absolute range accuracy",
        "UNVERIFIED",
    ]
    forbidden = [
        "C:" + "\\Users",
        "D:" + "\\",
        "Desk" + "top",
        "App" + "Data",
        "zig" + "xi",
        "COM" + "5",
    ]

    for snippet in required:
        assert snippet in report
    for snippet in forbidden:
        assert snippet not in report
