#pragma once

#include "board_config.h"

#define OPENRF1_RING_BUFFER_BYTES_TOTAL ( \
    (uint32_t)OPENRF1_RPLIDAR_RX_BUFFER_BYTES + \
    (uint32_t)OPENRF1_ESP32_RX_BUFFER_BYTES + \
    (uint32_t)OPENRF1_ESP32_TX_BUFFER_BYTES)

#define OPENRF1_ESTIMATED_STATIC_SRAM_BYTES ( \
    OPENRF1_RING_BUFFER_BYTES_TOTAL + \
    (uint32_t)OPENRF1_TELEMETRY_BUFFER_BYTES + \
    (uint32_t)512u)

OPENRF1_STATIC_ASSERT(openrf1_rplidar_buffer_power_of_two, (OPENRF1_RPLIDAR_RX_BUFFER_BYTES & (OPENRF1_RPLIDAR_RX_BUFFER_BYTES - 1u)) == 0u);
OPENRF1_STATIC_ASSERT(openrf1_esp32_rx_buffer_power_of_two, (OPENRF1_ESP32_RX_BUFFER_BYTES & (OPENRF1_ESP32_RX_BUFFER_BYTES - 1u)) == 0u);
OPENRF1_STATIC_ASSERT(openrf1_esp32_tx_buffer_power_of_two, (OPENRF1_ESP32_TX_BUFFER_BYTES & (OPENRF1_ESP32_TX_BUFFER_BYTES - 1u)) == 0u);
OPENRF1_STATIC_ASSERT(openrf1_static_sram_budget_margin, OPENRF1_ESTIMATED_STATIC_SRAM_BYTES < 8192u);
