[platformio]
default_envs = esp32c3_supermini

[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -DARDUINO_USB_CDC_ON_BOOT=1
build_unflags =
    -std=gnu++11
