#pragma once

#include <stdint.h>

/*
 * Unified rover-control hardware contract.
 *
 * Values marked UNKNOWN must stay unusable until an authoritative OpenRF1
 * schematic, connector definition, or controlled measurement resolves them.
 * Pure control modules must accept geometry and hardware backends at runtime;
 * they must not replace these sentinels with guessed GPIO assignments.
 */
#define OPENRF1_HARDWARE_UNKNOWN_I32 ((int32_t)-1)
#define OPENRF1_HARDWARE_UNKNOWN_U32 UINT32_MAX
#define OPENRF1_HARDWARE_UNKNOWN_TEXT "UNKNOWN"

#define OPENRF1_ROVER_MOTOR_COUNT ((uint8_t)4u)
#define OPENRF1_ROVER_ENCODER_COUNT ((uint8_t)4u)

/* Task input for software configuration; physical integration is UNVERIFIED. */
#define OPENRF1_JGB37_520_MIN_SUPPLY_MV ((uint32_t)6000u)
#define OPENRF1_JGB37_520_MAX_SUPPLY_MV ((uint32_t)12000u)
#define OPENRF1_ENCODER_MOTOR_SHAFT_PPR ((uint32_t)11u)
#define OPENRF1_GEAR_RATIO_NUMERATOR ((uint32_t)30u)
#define OPENRF1_GEAR_RATIO_DENOMINATOR ((uint32_t)1u)
#define OPENRF1_ENCODER_OUTPUT_SHAFT_PPR ((uint32_t)330u)
#define OPENRF1_ENCODER_QUADRATURE_MULTIPLIER ((uint32_t)4u)
#define OPENRF1_ENCODER_COUNTS_PER_OUTPUT_REV ((uint32_t)1320u)

/* Geometry is deliberately unresolved; it is supplied to mecanum at runtime. */
#define OPENRF1_WHEEL_RADIUS_MM OPENRF1_HARDWARE_UNKNOWN_I32
#define OPENRF1_HALF_WHEELBASE_MM OPENRF1_HARDWARE_UNKNOWN_I32
#define OPENRF1_HALF_TRACK_WIDTH_MM OPENRF1_HARDWARE_UNKNOWN_I32
#define OPENRF1_MAX_WHEEL_SPEED_MRAD_S OPENRF1_HARDWARE_UNKNOWN_I32
#define OPENRF1_MECANUM_ROLLER_LAYOUT OPENRF1_HARDWARE_UNKNOWN_I32
#define OPENRF1_MECANUM_GEOMETRY_READY ((uint8_t)0u)

/* Motor connector, PWM, direction, enable, and logical wheel mappings. */
#define OPENRF1_MOTOR_FRONT_LEFT_CONNECTOR OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_FRONT_LEFT_PWM_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_FRONT_LEFT_DIRECTION_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_FRONT_RIGHT_CONNECTOR OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_FRONT_RIGHT_PWM_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_FRONT_RIGHT_DIRECTION_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_REAR_LEFT_CONNECTOR OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_REAR_LEFT_PWM_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_REAR_LEFT_DIRECTION_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_REAR_RIGHT_CONNECTOR OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_REAR_RIGHT_PWM_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_REAR_RIGHT_DIRECTION_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_PWM_TIMER OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_ENABLE_SIGNAL OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_MOTOR_BRAKE_BEHAVIOR OPENRF1_HARDWARE_UNKNOWN_TEXT

/* Encoder connector, A/B channel, timer, and sign mappings. */
#define OPENRF1_ENCODER_FRONT_LEFT_A_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ENCODER_FRONT_LEFT_B_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ENCODER_FRONT_RIGHT_A_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ENCODER_FRONT_RIGHT_B_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ENCODER_REAR_LEFT_A_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ENCODER_REAR_LEFT_B_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ENCODER_REAR_RIGHT_A_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ENCODER_REAR_RIGHT_B_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ENCODER_TIMER_MAPPING OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ENCODER_DIRECTION_SIGNS OPENRF1_HARDWARE_UNKNOWN_TEXT

/* Future communication integration; no UART is selected by this foundation. */
#define OPENRF1_RPLIDAR_C1_UART OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_RPLIDAR_C1_UART_TX_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_RPLIDAR_C1_UART_RX_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ESP32_UART OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ESP32_UART_TX_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT
#define OPENRF1_ESP32_UART_RX_PIN OPENRF1_HARDWARE_UNKNOWN_TEXT

#define OPENRF1_MOTOR_HARDWARE_MAPPING_READY ((uint8_t)0u)
#define OPENRF1_ENCODER_HARDWARE_MAPPING_READY ((uint8_t)0u)
#define OPENRF1_RPLIDAR_C1_UART_MAPPING_READY ((uint8_t)0u)
#define OPENRF1_ESP32_UART_MAPPING_READY ((uint8_t)0u)
